### ISSUE TITLE
About the gate calculation

### ISSUE THREAD

**Issue by tomato151** [zerothi/ts-tbt-sisl-tutorial#10]
Hi， @zerothi,
I try to calculate the electronic transport properties of a graphene nanojunction with a charge gate using the Geometry.Charge block and I have two questions about the calculation details.

- Should the option SlabDipoleCorrection be chosen? In the Method part of your paper published in PCCP the slab dipole correction was used, however I did not find this option in the fdf file.

- If I put a charge -e in the gate plane, how to induce a charge +e in the graphene nanojunction to keep the whole system (the graphene nanojunction + gate) neutral?

Thanks for your kind help.
 
Regards,
Haoyang

**Comment by zerothi** [comment]
1. Yes, you should use the dipole correction. They were also used for the calculation in mention.
2. The system is charge-neutral in total when using `Geometry.Charge`, as is shown in the paper in question, you add a charge `g` on the gate, and remove the same charge from the system.

**Comment by tomato151** [comment]
I notice that if the neutral system has 1148 electrons, when using 
```
%block Geometry.Charge
 plane -2.0 charge
   gauss 1. 2. Ang
    0. 20.0 0. Ang
    0. 1. 0.
%endblock Geometry.Charge
```
There is a line in output
`transiesta: Charge distribution, target =  1150.00000`
How do the program realize this? Is the Fermi level of the electrodes shifted?

Thank you!

**Comment by zerothi** [comment]
> 2. The system is charge-neutral in total when using `Geometry.Charge`, as is shown in the paper in question, you add a charge `g` on the gate, and remove the same charge from the system.

In the above case you put `-2` electrons on the gate, and then add 2 electrons to the system. Effectively charging the system, while the total simulation cell is charge neutral (due to the gate).

**Comment by tomato151** [comment]
Thanks, I have understood.
