### ISSUE TITLE
Error running %pdoc sisl.Geometry.tile help(sisl.Geometry.tile)

### ISSUE THREAD

**Issue by mathew-physics** [zerothi/ts-tbt-sisl-tutorial#13]
Object `sisl.Geometry.tile` not found.
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-3-9d46e3075131> in <module>
      1 get_ipython().run_line_magic('pdoc', 'sisl.Geometry.tile')
----> 2 help(sisl.Geometry.tile)

NameError: name 'sisl' is not defined

**Comment by zerothi** [comment]
Please provide more information... It looks like you didn't execute all cells


Also, you can't just give an error message and expect me to know which tutorial you are writing about... So please provide more details.

**Comment by mathew-physics** [comment]
I was going through the initial part of the tutorial. The error happened at the cell after _For instance to get help regarding a specific function in a class, you may invoke either of the following 2 lines of code, whichever you prefer (the first will divide the current window with this and a help window, while the other will print out)_:

As you mentioned, the error was because I didn't execute all cells. I some how missed the _import sisl_ at the top

Thank you for the immediate feedback

**Comment by zerothi** [comment]
Great! :)
