### ISSUE TITLE
siesta band structure + selected fatbands

### ISSUE THREAD

**Issue by ElwiraW** [zerothi/ts-tbt-sisl-tutorial#16]
I've just started learning sisl. I wonder if it is possible to get band structure with selected fatbands. I include example of a figure I mean obtained from VASP calculations in p4v. 

Thank you for help.

Elwira 
 
![gd-graph-sic_und_gr_C32-39-p_elec](https://user-images.githubusercontent.com/105803852/169073536-2c470277-7d15-4437-ac36-b605a4e4584c.png)

**Comment by zerothi** [comment]
Please post this question to the sisl development site :)

This is related to the tutorials, e.g. if you want to add a new tutorial or have questions related to a specific tutorial.

I'll close this ticket and let you open a new one at zerothi/sisl :)

Thanks!
