### ISSUE TITLE
<< 2018 Tutorial installation in Debian 9.8 >>

### ISSUE THREAD

**Issue by icamps** [zerothi/ts-tbt-sisl-tutorial#2]
Hello,

Dear @zerothi ,

Sorry to bother you with this issue, We installed the tutorial using the installation script and, at the end, we got the following message:

```
This script assumes you are using Python 2.7

 Will try and run sisl
    import sisl ; print(sisl.geom.graphene())
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/icamps/.local/lib/python2.7/site-packages/sisl/__init__.py", line 90, in <module>
    from . import linalg
  File "/home/icamps/.local/lib/python2.7/site-packages/sisl/linalg/__init__.py", line 30, in <module>
    from .base import *
  File "/home/icamps/.local/lib/python2.7/site-packages/sisl/linalg/base.py", line 5, in <module>
    from numpy import atleast_1d, atleast_2d
  File "/home/icamps/.local/lib/python2.7/site-packages/numpy/__init__.py", line 140, in <module>
    from . import _distributor_init
ImportError: cannot import name _distributor_init
Failed running sisl, please mail the organizer with the error message (unless some of the installations failed)
```

I did not get any other messages.

Thanks in advance,

Camps

**Comment by zerothi** [comment]
It seems like this file is removed during the installation.

Could you please do:
```bash
touch /home/icamps/.local/lib/python2.7/site-packages/numpy/_distributor_init.py
```
and re-run.

**Comment by icamps** [comment]
Should I re-run the installation `./install_tutorial.sh install`?

**Comment by zerothi** [comment]
No that should not be necessary, try and see without.

**Comment by zerothi** [comment]
@icamps did you try? And did it work ;)

**Comment by icamps** [comment]
@zerothi Yesterday and today I had/have a lot of classes :( 
As soon as I finish with my classes I will test and return to you.

**Comment by zerothi** [comment]
@icamps no worries ;)

**Comment by zerothi** [comment]
@icamps did it work ;) ?

**Comment by icamps** [comment]
Hi @zerothi.

Thanks for the following.

I am stuck compiling tbtrans, that I suppose it is needed to run the tutorials.

I used a clean arch.make (a copy of that one that came for Intel compilers) but gave me the same errors about bad INCLUDE path.

(In between, I got the same error when I tried to compile gnubands, that at the end, I compiled manually, without using make).

Regards,

Camps

**Comment by zerothi** [comment]
Could you share the arch.make here?

**Comment by icamps** [comment]
Here there are.

The file `arch.make_Intel.txt` correspond to a very clean arch.make (from distribution files).
The file `arch.make_orange.txt` correspond to one that I used to successfully compile SIESTA (siesta-4.1-b4 and transiesta).

(The final txt is just to upload here).

[arch.make_Intel.txt](https://github.com/zerothi/ts-tbt-sisl-tutorial/files/3182787/arch.make_Intel.txt)
[arch.make_orange.txt](https://github.com/zerothi/ts-tbt-sisl-tutorial/files/3182788/arch.make_orange.txt)

**Comment by zerothi** [comment]
And what is the error for `arch.make_orange.txt`?

**Comment by icamps** [comment]
Here it is.
[nohup.out.txt](https://github.com/zerothi/ts-tbt-sisl-tutorial/files/3182967/nohup.out.txt)

**Comment by zerothi** [comment]
Could you try and add:

```make
FPPFLAGS += -I.
```
to your `arch.make` file?

**Comment by icamps** [comment]
I got the same errors.
[nohup.out.txt](https://github.com/zerothi/ts-tbt-sisl-tutorial/files/3183062/nohup.out.txt)

**Comment by zerothi** [comment]
Could you try and do:
```bash
make parallel.o
make
```

**Comment by zerothi** [comment]
@icamps is there any progress here? Or do you still have issues?

Otherwise I'll close this next week! :)

**Comment by icamps** [comment]
Hi @zerothi , we could compile/install it. Sorry for the delay.

**Comment by icamps** [comment]
Solved.
